### ISSUE TITLE
Static variables in MainActivity

### ISSUE THREAD

**Issue by theKidOfArcrania** [yourPISD/yourpisd#25]
Would you explain your rationale behind using static variables and static classes (rather than using instance classes and instance variables)?

**Comment by sid-kap** [comment]
The static classes thing is an Android quirk. Fragments must be either standalone classes, or static inner classes. (See the discussion on these StackOverflow posts: [\[1\]](http://stackoverflow.com/questions/22190797/what-is-the-design-logic-behind-fragments-as-static-inner-classes-vs-standalone) [\[2\]](http://stackoverflow.com/questions/15571010/fragment-inner-class-should-be-static).)

Since `MainActivityFragment` is a static class, for it to access variables in `MainActivity`, they must be static as well.

**Comment by theKidOfArcrania** [comment]
Okay thanks.
