### ISSUE TITLE
Release version 4.0?

### ISSUE THREAD

**Issue by sid-kap** [yourPISD/yourpisd#29]
Hey @theKidOfArcrania and @creativitRy, if you guys are interested in releasing v4.0 sometime soon, just let me know and I'll add you guys to the Google Play developer account. I think you'll need to sign the apk with a special key or something. I don't remember how to do that, but we can ask @hanli1.

Btw, what work is remaining before we want to release?

**Comment by theKidOfArcrania** [comment]
This release we will need to mark as a BETA version only because of several reasons:
- We don't know what will happen after the 1st Nine Weeks how it may pan out. (Where the grades for next nine weeks will be located, whether if they are combined, or if they are grouped by nine-weeks).
- There has been several edge cases pointed out, for example, Issue #28 that has not been originally accounted for. We will need to give a larger general audience in order address other edge cases that may not have been known. 
- There has been many changes that have not and cannot be fully tested because the values are limited to just our (@creativitRy and @theKidOfArcrania) grades. 

Here's a list of the things we might (or might not do) for this next release in descending priority:
- **Licensing** (Issue #19) This may be the most crucial part to complete before the next release, how we are going to do licensing and putting that header on every file.
- **Fixing Edge Cases** (Issue #28 (What happens if the grade is X?) )
- **UI Changes** (Issue #26 (Moving last-updated to subtitle), #27 (Profile picture) ), these are bugs or fixes to the current UI experience, although I'm not as solid on how the UI works on the android. Out of all the UI enhances or fixes I found, these are probably the most crucial parts concerning the UI.
- **Parent issues** (Issue #11 (having multiple students) ) (apparently, the parents do not directly login to gradebook pisd, so we will need to create a case for that). Another issue I just found is that the formatting for parent grade viewer is slightly different. As of now, we do NOT have support for parents, this may or may not be fixed.

**Comment by theKidOfArcrania** [comment]
At least for the beta version, I'm probably going to just disable parent viewing (for now) so that we can push the app ASAP

**Comment by sid-kap** [comment]
That sounds fine

Is it ready to publish?

**Comment by sid-kap** [comment]
BTW, I think it might be a good idea to just push out to everyone instead of just beta, so that it will reach more people. Some bugs remain but I don't think it's a big deal, considering that it's not working at all now. Ultimately, it's your call though

**Comment by theKidOfArcrania** [comment]
Okay this version is ready for deployment, what would I need to do at this point?
